myProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path
from . import views

app_name= 'ToDo'

urlpatterns = [
    path("", views.home, name='index'),
    path("add", views.addTask, name='add'),
    path("<int:todo_id>/update", views.update, name='update'),
    path("<int:todo_id>/delete/", views.delete, name="delete"),
    path("deleteAll", views.deleteAll, name='deleteAll'),
    path("<int:todo_id>/updateredirect", views.updateredirect, name='updateredirect')
]

ToDo/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Todo(models.Model):
    todo_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

todo/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone

# Create your models here.

class Todo(models.Model):
    todo_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

ToDo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from .models import Todo

# Create your views here.
def home(request):
    todo_items = Todo.objects.all().order_by("-created_at")
    return render(request, 'ToDo/index.html', {'todo_items': todo_items})

@csrf_exempt
def addTask(request):
    Todo.objects.create(title=request.POST['task'])
    # Todo.objects.all().delete()
    # print(request.POST)
    return HttpResponseRedirect(reverse("ToDo:index"))

@csrf_exempt
def update(request, todo_id):
    todo = Todo.objects.get(todo_id=todo_id)
    todo.title = request.POST['task']
    todo.save()
    return HttpResponseRedirect(reverse("ToDo:index"))

@csrf_exempt
def updateredirect(request, todo_id):
    task = Todo.objects.get(todo_id=todo_id)
    return render(request, 'ToDo/update.html', {'task': task, 'todo_id': todo_id})

@csrf_exempt
def delete(request, todo_id):
    Todo.objects.filter(todo_id=todo_id).delete()
    return HttpResponseRedirect(reverse("ToDo:index"))

@csrf_exempt
def deleteAll(request):
    Todo.objects.all().delete()
    return HttpResponseRedirect(reverse("ToDo:index"))

todo/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from .models import Todo

# Create your views here.
def home(request):
    todo_items = Todo.objects.all().order_by("-created_at")
    return render(request, 'ToDo/index.html', {'todo_items': todo_items})

@csrf_exempt
def addTask(request):
    Todo.objects.create(title=request.POST['task'])
    # Todo.objects.all().delete()
    # print(request.POST)
    return HttpResponseRedirect(reverse("ToDo:index"))

@csrf_exempt
def update(request, todo_id):
    todo = Todo.objects.get(todo_id=todo_id)
    todo.title = request.POST['task']
    todo.save()
    return HttpResponseRedirect(reverse("ToDo:index"))

@csrf_exempt
def updateredirect(request, todo_id):
    task = Todo.objects.get(todo_id=todo_id)
    return render(request, 'ToDo/update.html', {'task': task, 'todo_id': todo_id})

@csrf_exempt
def delete(request, todo_id):
    Todo.objects.filter(todo_id=todo_id).delete()
    return HttpResponseRedirect(reverse("ToDo:index"))

@csrf_exempt
def deleteAll(request):
    Todo.objects.all().delete()
    return HttpResponseRedirect(reverse("ToDo:index"))

todo/templates/ToDo/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/icon.jpg' %}">
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    {% block title %}
        <title>Todo list</title>
    {% endblock title%}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-primary" data-bs-theme="dark">
        <!-- Navbar content -->
        <a class="navbar-brand" href="#">ToDo App</a>
    </nav>
    <div class="container">
        {% block body %} {% endblock %}
    </div>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

todo/templates/ToDo/index.html
{% extends 'ToDo/base.html' %}

{% block body %}
<div class="rol mt-4">
    <div class="col">
        <h2>Add Task</h2>
        <form class="form-inline" action="{% url 'ToDo:add' %}" method="post">
            <input type="text" name="task" class="form-control mb-2 mr-sm-2" placeholder="Type the task here.." required>
            <button type="submit" class="btn btn-primary mb-2">Submit </button>
        </form>
    </div>
</div>
<div class="float-end">
    <form action="{% url 'ToDo:deleteAll' %}" method="post">
        <button type="submit" class="btn btn-sm btn-danger ">Delete All</button> 
    </form>
</div>
<div class="row mt-5">
    <div class="col">
        <ul class="list-group">
            {% for todo_item in  todo_items %}
                <li class="list-group-item">{{ todo_item.title }}
                    <div class="float-end"> 
                        <form action="{% url 'ToDo:updateredirect' todo_item.todo_id %}" method="post">
                            <button type="submit" class="btn btn-sm btn-secondary">Update</button> 
                        </form>
                        <form action="{% url 'ToDo:delete' todo_item.todo_id %}" method="post">
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button> 
                        </form>
                    </div>
                </li>
            {% endfor %}
          </ul>
    </div>
</div>
{% endblock %}

todo/templates/ToDo/update.html
{% extends 'ToDo/base.html' %}

{% block body %}
<div class="row mt-4">
    <div class="col">
        <h2>Update Task: '{{ task.title }}'</h2>
        <form class="form-inline" action="{% url 'ToDo:update' todo_id %}" method="post">
            <input type="text" name="task" class="form-control mb-2 mr-sm-2" placeholder="Type the task here..">
            <button type="submit" class="btn btn-primary mb-2">Update</button>
        </form>
    </div>
</div>
{% endblock %}